spring.application.name=backend

server.port=8080

spring.security.oauth2.client.registration.google.client-id=417557972692-5h3igi2cqouedc4onujmvklggganug8n.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
